---
kind: pipeline
type: docker
name: verify-pr
steps:
- name: install
  image: danlynn/ember-cli:4.8.0
  commands:
  - npm ci
- name: lint
  image: danlynn/ember-cli:4.8.0
  commands:
  - npm run lint
- name: test
  image: danlynn/ember-cli:4.8.0
  failure: ignore
  commands:
  - npm run test:ember
trigger:
  event:
    - pull_request
---
kind: pipeline
type: docker
name: verify-build
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: lblod/frontend-mow-registry
    dry_run: true
    purge: true
---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: lblod/frontend-mow-registry
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - master
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: release
steps:
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: lblod/frontend-mow-registry
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
data: JLLn5K6iiMS48vsVfn4gduKeZkIuuO+BRBF4a/sgtctYT1VfyPuzZg==
---
kind: secret
name: docker_password
data: H6mK+RhCOvswvvZcy2xfRsxEy7XJ2HCg15mbOcmPFBiz3+b/gB+YuNLo0NuB6Sx6S6CZb/EPI45Vm+4/qK23Qg==
---
kind: signature
hmac: e40fef208bf9e41268e01b7e1b978da41d818beb00f4f57dfc1a8b1b2deb99dd

...
